stages:
  - prepare
  - build

.submodule_base: &submodule
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

prepare_catch2:
  <<: *submodule
  stage: prepare
  script:
    - mkdir -p cmakefiles_gcc/3rdparty/Catch2
    - cd cmakefiles_gcc/3rdparty/Catch2
    - >
      cmake
          -DCMAKE_TOOLCHAIN_FILE=~/mingw-w64-i686.cmake
          -DCMAKE_BUILD_TYPE=Release
          -DBUILD_TESTING=OFF
          -DCMAKE_INSTALL_PREFIX=../../../3rdparty/Catch2/dist
          ../../../3rdparty/Catch2
    - cmake --build . --target install

build:
  <<: *submodule
  stage: build
  script:
    - mkdir -p cmakefiles_gcc/sitl
    - cd cmakefiles_gcc/sitl
    - >
      cmake
          -DCMAKE_TOOLCHAIN_FILE=~/mingw-w64-i686.cmake
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_INSTALL_PREFIX=../../dist
          ../../
    - cmake --build . --target install
  artifacts:
    paths:
      - dist
